### PR TITLE
Update PHP version to 8.0

### PR DESCRIPTION
**Pull request by ericHao22**

### CODE REVIEW

**Comment by ericHao22** [comment]
[Laravel Package Template: Update PHP version to 8.0](https://trello.com/c/hrDWBKCE/585-laravel-package-template-update-php-version-to-80)

**Review by FishChen1202 — APPROVED** [review]
r+, thanks!

**Review by moon-brillar — APPROVED** [review]
r+ thanks!!

**Review by koshuang — APPROVED** [review]
r+, thanks!

**Pull request merged**
